### PR TITLE
added asterisk repo

### PR DESCRIPTION
**Pull request by garrettrowell**

### CODE REVIEW

**Comment by jmslagle** [comment]
Spec test?

Sent on the new Sprint Network from my Samsung Galaxy S®4.

<div>-------- Original message --------</div><div>From: Garrett Rowell notifications@github.com </div><div>Date:10/27/2014  5:48 PM  (GMT-05:00) </div><div>To: jmslagle/puppet-jslagle-repos puppet-jslagle-repos@noreply.github.com </div><div>Subject: [puppet-jslagle-repos] added asterisk repo (#1) </div><div>
</div>You can merge this Pull Request by running

  git pull https://github.com/garrettrowell/puppet-jslagle-repos master
Or view, comment on, or merge it at:

  https://github.com/jmslagle/puppet-jslagle-repos/pull/1

Commit Summary

added asterisk repo
File Changes

A manifests/asterisk.pp (11)
A manifests/yum/asterisk.pp (40)
Patch Links:

https://github.com/jmslagle/puppet-jslagle-repos/pull/1.patch
https://github.com/jmslagle/puppet-jslagle-repos/pull/1.diff

**Comment by garrettrowell** [comment]
Ill write one. would that be why travis is failing?

**Comment by jmslagle** [comment]
Maybe :)

Or I broke it.

Jason

**Comment by garrettrowell** [comment]
initially my tests were helping break travis, but the only remaining failures are:

rspec ./spec/classes/repos_apt_puppetlabs_spec.rb:10 # repos::apt::puppetlabs Should contain sources 
rspec ./spec/classes/repos_spec.rb:31 # repos Ubuntu Tests Include puppetlabs

**Pull request merged**
